import test from'node:test';import assert from'node:assert/strict';import{spawn}from'node:child_process';import fs from'node:fs/promises';import os from'node:os';import path from'node:path';
test('management actions require an administrator session and keep working with one',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'arrsight-action-')),port=20150+Math.floor(Math.random()*200),origin=`http://127.0.0.1:${port}`;let child,output='';try{child=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,CONFIG_DIR:dir,PORT:String(port)},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('startup timeout')),5000);child.stdout.on('data',data=>{output+=data;if(output.includes('listening')){clearTimeout(timer);resolve();}});});const code=output.match(/setup code .*: (\S+)/)?.[1];assert.ok(code);
let response=await fetch(`${origin}/api/config`,{method:'PUT',headers:{origin,'content-type':'application/json'},body:JSON.stringify({setupCode:code,adminPassword:'a secure password',locale:'en',managementMode:'containers',containers:['sonarr']})});assert.equal(response.status,200);
const post=(body,cookie)=>fetch(`${origin}/api/action`,{method:'POST',headers:{origin,'content-type':'application/json',...(cookie?{cookie}:{})},body:JSON.stringify(body)});
for(const action of [{action:'restart-container',target:'sonarr'},{action:'sonarr-missing-search'},{action:'run-verifier'}]){response=await post(action);assert.equal(response.status,401);assert.equal((await response.json()).code,'authentication_required');}
response=await post({action:'restart-container',target:'sonarr'},'arrsight_session=forged');assert.equal(response.status,401);
response=await fetch(`${origin}/api/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({password:'a secure password'})});const cookie=response.headers.get('set-cookie').split(';')[0];
response=await post({action:'restart-container',target:'sonarr'},cookie);const restarted=await response.json();assert.ok(![401,403].includes(response.status));assert.equal(restarted.action,'restart-container');
response=await post({action:'run-verifier'},cookie);assert.equal(response.status,403);}finally{child?.kill('SIGTERM');await fs.rm(dir,{recursive:true,force:true});}});
