import test from 'node:test';import assert from 'node:assert/strict';import{hashPassword,verifyPassword,sessionStore,cookieValue,SESSION_TTL_MS,requestIsSecure,sessionCookie,clearedSessionCookie}from'../lib/auth.js';
test('administrator passwords are strongly hashed',async()=>{const stored=await hashPassword('correct horse battery');assert.match(stored,/^scrypt:/);assert.equal(stored.includes('correct horse'),false);assert.equal(await verifyPassword('correct horse battery',stored),true);assert.equal(await verifyPassword('wrong password',stored),false);});
test('sessions expire and cookies parse',()=>{const original=Date.now;let now=100;Date.now=()=>now;try{const store=sessionStore(10),token=store.create();assert.equal(store.valid(token),true);now=111;assert.equal(store.valid(token),false);assert.equal(cookieValue(`a=b; arrsight_session=${token}`),token);}finally{Date.now=original;}});
test('secure detection needs an encrypted socket or explicit proxy opt-in',()=>{const req=(headers={},encrypted=false)=>({headers,socket:{encrypted}});
const original=process.env.ARRSIGHT_TRUST_PROXY;
try{
delete process.env.ARRSIGHT_TRUST_PROXY;
assert.equal(requestIsSecure(req({},true)),true);
assert.equal(requestIsSecure(req()),false);
assert.equal(requestIsSecure(req({'x-forwarded-proto':'http'})),false);
assert.equal(requestIsSecure(req({'x-forwarded-proto':'https'})),false);
assert.equal(requestIsSecure(req({'x-forwarded-proto':'HTTPS, http'})),false);
process.env.ARRSIGHT_TRUST_PROXY='true';
assert.equal(requestIsSecure(req()),false);
assert.equal(requestIsSecure(req({'x-forwarded-proto':'http'})),false);
assert.equal(requestIsSecure(req({'x-forwarded-proto':'https'})),true);
assert.equal(requestIsSecure(req({'x-forwarded-proto':'HTTPS, http'})),true);
process.env.ARRSIGHT_TRUST_PROXY='1';
assert.equal(requestIsSecure(req({'x-forwarded-proto':'https'})),false);
}finally{if(original===undefined)delete process.env.ARRSIGHT_TRUST_PROXY;else process.env.ARRSIGHT_TRUST_PROXY=original;}});
test('session cookies carry Secure only when requested',()=>{assert.equal(sessionCookie('tok'),`arrsight_session=tok; HttpOnly; SameSite=Strict; Path=/; Max-Age=${SESSION_TTL_MS/1000}`);assert.equal(sessionCookie('tok',{secure:true}),`arrsight_session=tok; HttpOnly; SameSite=Strict; Path=/; Max-Age=${SESSION_TTL_MS/1000}; Secure`);assert.equal(clearedSessionCookie(false),'arrsight_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');assert.equal(clearedSessionCookie(true),'arrsight_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0; Secure');});
