import test from'node:test';import assert from'node:assert/strict';import{spawn}from'node:child_process';import fs from'node:fs/promises';import os from'node:os';import path from'node:path';
import{normalizeConfigInput,validateConfig,migrateConfig}from'../lib/config.js';
test('link normalization accepts sane maps and rejects unsafe keys and urls',()=>{const good=normalizeConfigInput({links:{Sonarr:'http://sonarr:8989','Backup Plex':'https://plex.example.com/path'}});assert.deepEqual(good.errors,[]);assert.deepEqual(good.value.links,{Sonarr:'http://sonarr:8989','Backup Plex':'https://plex.example.com/path'});
const bad=normalizeConfigInput(JSON.parse('{"links":{"__proto__":"https://example.com"}}'));assert.ok(bad.errors.includes('invalid_type:links.__proto__'));
assert.ok(normalizeConfigInput({links:{Bad:'ftp://example.com'}}).errors.includes('invalid_url:links.Bad'));
assert.ok(normalizeConfigInput({links:{Cred:'https://user:pass@example.com'}}).errors.includes('invalid_url:links.Cred'));
assert.ok(normalizeConfigInput({links:{'':('https://example.com')}}).errors.length);
assert.ok(normalizeConfigInput({links:{Long:'x'.repeat(2049)}}).errors.length);
assert.ok(normalizeConfigInput({links:{NotUrl:42}}).errors.length);
assert.ok(normalizeConfigInput({links:['https://example.com']}).errors.includes('invalid_type:links'));
assert.ok(validateConfig(migrateConfig({links:{Bad:'javascript:alert(1)'}})).includes('invalid_url:links.Bad'));
assert.deepEqual(validateConfig(migrateConfig({links:{Ok:'https://example.com'}})),[]);});
test('links add edit and remove round-trip through config save and load',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'arrsight-links-')),port=20800+Math.floor(Math.random()*200),origin=`http://127.0.0.1:${port}`;let child,output='';try{child=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,CONFIG_DIR:dir,PORT:String(port)},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('startup timeout')),5000);child.stdout.on('data',data=>{output+=data;if(output.includes('listening')){clearTimeout(timer);resolve();}});});const code=output.match(/setup code .*: (\S+)/)?.[1];assert.ok(code);
let response=await fetch(`${origin}/api/config`,{method:'PUT',headers:{origin,'content-type':'application/json'},body:JSON.stringify({setupCode:code,adminPassword:'a secure password',locale:'en',managementMode:'monitoring'})});assert.equal(response.status,200);
response=await fetch(`${origin}/api/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({password:'a secure password'})});const cookie=response.headers.get('set-cookie').split(';')[0];
const putLinks=(links)=>fetch(`${origin}/api/config`,{method:'PUT',headers:{origin,'content-type':'application/json',cookie},body:JSON.stringify({links})});
const getLinks=async()=>(await (await fetch(`${origin}/api/config`,{headers:{cookie}})).json()).config.links;
let put=await putLinks({Sonarr:'http://sonarr:8989'});assert.equal(put.status,200);assert.deepEqual(await getLinks(),{Sonarr:'http://sonarr:8989'});
put=await putLinks({Sonarr:'http://sonarr:9090',Radarr:'http://radarr:7878'});assert.equal(put.status,200);assert.deepEqual(await getLinks(),{Sonarr:'http://sonarr:9090',Radarr:'http://radarr:7878'});
put=await putLinks({Radarr:'http://radarr:7878'});assert.equal(put.status,200);assert.deepEqual(await getLinks(),{Radarr:'http://radarr:7878'});
put=await putLinks({});assert.equal(put.status,200);assert.deepEqual(await getLinks(),{});
put=await putLinks({Bad:'ftp://example.com'});assert.equal(put.status,400);
put=await putLinks(JSON.parse('{"__proto__":"https://example.com"}'));assert.equal(put.status,400);}finally{child?.kill('SIGTERM');await fs.rm(dir,{recursive:true,force:true});}});
