import test from'node:test';import assert from'node:assert/strict';import{spawn}from'node:child_process';import fs from'node:fs/promises';import os from'node:os';import path from'node:path';
test('initial setup creates admin authentication and redacts configuration',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'arrsight-auth-')),port=19600+Math.floor(Math.random()*300),origin=`http://127.0.0.1:${port}`;let child,output='';try{child=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,CONFIG_DIR:dir,PORT:String(port)},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('startup timeout')),5000);child.stdout.on('data',data=>{output+=data;if(output.includes('listening')){clearTimeout(timer);resolve();}});});const code=output.match(/setup code .*: (\S+)/)?.[1];assert.ok(code);let response=await fetch(`${origin}/api/config`,{method:'PUT',headers:{origin,'content-type':'application/json'},body:JSON.stringify({setupCode:code,adminPassword:'a secure password',locale:'en',managementMode:'monitoring'})});assert.equal(response.status,200);response=await fetch(`${origin}/api/config`);assert.equal(response.status,401);response=await fetch(`${origin}/api/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({password:'wrong password'})});assert.equal(response.status,401);response=await fetch(`${origin}/api/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({password:'a secure password'})});assert.equal(response.status,200);const cookie=response.headers.get('set-cookie').split(';')[0];response=await fetch(`${origin}/api/config`,{headers:{cookie}});const value=await response.json();assert.equal(response.status,200);assert.equal(value.config.admin,undefined);assert.equal(JSON.stringify(value).includes('passwordHash'),false);}finally{child?.kill('SIGTERM');await fs.rm(dir,{recursive:true,force:true});}});
test('frontend publicConfig round-trip saves during setup and settings re-save',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'arrsight-roundtrip-')),port=19950+Math.floor(Math.random()*200),origin=`http://127.0.0.1:${port}`,services=['sonarr','radarr','bazarr','plex','jellyfin','infinidysk','nzbdav'];let child,output='';try{child=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,CONFIG_DIR:dir,PORT:String(port)},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('startup timeout')),5000);child.stdout.on('data',data=>{output+=data;if(output.includes('listening')){clearTimeout(timer);resolve();}});});const code=output.match(/setup code .*: (\S+)/)?.[1];assert.ok(code);
const wizardPayload=(value)=>{const payload=structuredClone({...value.config,locale:'en'});for(const name of services)if(payload[name])delete payload[name].secretConfigured;return payload;};
let response=await fetch(`${origin}/api/config`);const first=wizardPayload(await response.json());first.sonarr={...first.sonarr,enabled:true,url:'http://sonarr:8989',apiKey:'test-key'};
response=await fetch(`${origin}/api/config`,{method:'PUT',headers:{origin,'content-type':'application/json'},body:JSON.stringify({...first,setupCode:code,adminPassword:'a secure password'})});const saved=await response.json();assert.equal(response.status,200);assert.equal(saved.config.sonarr.apiKey,undefined);assert.equal(saved.config.sonarr.secretConfigured,true);
response=await fetch(`${origin}/api/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({password:'a secure password'})});const cookie=response.headers.get('set-cookie').split(';')[0];
response=await fetch(`${origin}/api/config`,{headers:{cookie}});assert.equal(response.status,200);const again=wizardPayload(await response.json());for(const field of ['configVersion','productName','port'])assert.ok(field in again,`payload must echo ${field}`);again.locale='nl';
response=await fetch(`${origin}/api/config`,{method:'PUT',headers:{origin,'content-type':'application/json',cookie},body:JSON.stringify(again)});const resaved=await response.json();assert.equal(response.status,200);assert.equal(resaved.config.locale,'nl');assert.equal(resaved.config.sonarr.secretConfigured,true);}finally{child?.kill('SIGTERM');await fs.rm(dir,{recursive:true,force:true});}});
